// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYcZV0eHYZ3lIQfZi--vZJgfYJeDaFx4',
    appId: '1:947539259472:web:f1f9925e12528cdfe92155',
    messagingSenderId: '947539259472',
    projectId: 'fir-88026',
    authDomain: 'fir-88026.firebaseapp.com',
    storageBucket: 'fir-88026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnz81wETq-KJMGUZnXbjRwwQnch8V8A7w',
    appId: '1:947539259472:android:d38b6c5331eebef0e92155',
    messagingSenderId: '947539259472',
    projectId: 'fir-88026',
    storageBucket: 'fir-88026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDti15aqqxcKSM5Z-B-jKrDc8Y6BqOt7zA',
    appId: '1:947539259472:ios:17c808303d30d70fe92155',
    messagingSenderId: '947539259472',
    projectId: 'fir-88026',
    storageBucket: 'fir-88026.appspot.com',
    iosBundleId: 'com.example.amazonMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDti15aqqxcKSM5Z-B-jKrDc8Y6BqOt7zA',
    appId: '1:947539259472:ios:22a92b06a3b1b1cde92155',
    messagingSenderId: '947539259472',
    projectId: 'fir-88026',
    storageBucket: 'fir-88026.appspot.com',
    iosBundleId: 'com.example.amazonMobile.RunnerTests',
  );
}
